-- AUTO-GENERATED by scripts/gen-seed.ts — do not edit by hand.
-- Run after schema.sql. Safe to re-run (on conflict do nothing).

insert into public.categories
  (slug,title,title_bn,description,section_type,parent_slug,group_key,sort_order,show_on_home,home_limit,accent,is_active)
values
  ('online-portals','Top Online Bangla News Portals','অনলাইন বাংলা নিউজ পোর্টাল','The most-read online news portals in Bangla. Since the nineties, online portals have become the fastest way Bengali-speaking readers follow breaking news, worldwide and at home.','outlet_grid',null,'portals',10,true,12,null,true),
  ('national-newspapers','All Bangla Daily Newspapers','সকল বাংলা দৈনিক পত্রিকা','Since 1818, Bangla daily newspapers have grown in reach and reputation. This is the full index of national dailies covering politics, business, sport and culture 24/7.','outlet_grid',null,'newspapers',20,true,12,null,true),
  ('local-newspaper','Local Newspaper by Division','বিভাগভিত্তিক স্থানীয় পত্রিকা','Bangladesh has eight divisions — Dhaka, Mymensingh, Sylhet, Chattogram, Rangpur, Khulna, Rajshahi and Barisal. Each has its own regional newspapers reporting local news around the clock.','division_grid',null,'regional',30,true,12,null,true),
  ('tv-news','Bangla TV News Channels','বাংলা টিভি নিউজ চ্যানেল','The most-watched Bangla television news channels — live news, talk shows and breaking coverage from Bangladesh''s leading broadcasters.','outlet_grid',null,'tv',35,true,12,null,true),
  ('fm-radio','Top Bangla FM Radio','শীর্ষ বাংলা এফএম রেডিও','FM radio is a popular medium for young Bengali listeners — entertainment, music and news. These stations broadcast in Bangla from across Bangladesh.','outlet_grid',null,'radio',40,true,12,null,true),
  ('government-portals','Bangladesh Government Portals','বাংলাদেশ সরকারি পোর্টাল','Official government web portals of Bangladesh — the national portal and the ministries that publish public services, notices and information.','outlet_grid',null,'government',50,true,12,null,true),
  ('job-portals','Popular Bangla Job Sites','জনপ্রিয় চাকরির সাইট','Job portals connect employers and job seekers. These are the most popular Bangladeshi job sites for finding work or hiring staff.','outlet_grid',null,'jobs',60,true,12,null,true),
  ('english-newspapers','Bangladeshi English Newspapers','বাংলাদেশি ইংরেজি সংবাদপত্র','Leading English-language daily newspapers published from Bangladesh, widely read at home and by the diaspora.','outlet_grid',null,'english',70,true,12,null,true),
  ('stock-market','Stock Market News','শেয়ার বাজার সংবাদ','Stock market and business news sources covering the Dhaka and Chittagong exchanges, listed companies and the wider economy.','outlet_grid',null,'stock',80,true,12,null,true),
  ('assam-newspapers','Best Assam Newspapers','আসামের সেরা সংবাদপত্র','Assam, India is home to many Bengali-speaking readers. These well-known Assamese newspapers have a long history and wide readership.','outlet_grid',null,'assam',90,true,12,null,true),
  ('epaper','Bangla ePaper Editions','বাংলা ই-পেপার','Digital replica ePaper editions of the major Bangla dailies — read the printed paper online, page by page.','outlet_grid',null,'epaper',100,true,12,null,true),
  ('international-newspapers','International Newspapers','আন্তর্জাতিক সংবাদপত্র','Major international newspapers and global news sources in one place.','outlet_grid',null,'international',95,false,12,null,true),
  ('dhaka-division','Dhaka Division','ঢাকা বিভাগ',null,'outlet_grid','local-newspaper','regional',1,false,12,'#E8A100',true),
  ('mymensingh-division','Mymensingh Division','ময়মনসিংহ বিভাগ',null,'outlet_grid','local-newspaper','regional',2,false,12,'#E86FB0',true),
  ('sylhet-division','Sylhet Division','সিলেট বিভাগ',null,'outlet_grid','local-newspaper','regional',3,false,12,'#DB4A24',true),
  ('chattogram-division','Chattogram Division','চট্টগ্রাম বিভাগ',null,'outlet_grid','local-newspaper','regional',4,false,12,'#2BB6C9',true),
  ('rangpur-division','Rangpur Division','রংপুর বিভাগ',null,'outlet_grid','local-newspaper','regional',5,false,12,'#7BC043',true),
  ('khulna-division','Khulna Division','খুলনা বিভাগ',null,'outlet_grid','local-newspaper','regional',6,false,12,'#B57BE0',true),
  ('rajshahi-division','Rajshahi Division','রাজশাহী বিভাগ',null,'outlet_grid','local-newspaper','regional',7,false,12,'#4AA3DB',true),
  ('barisal-division','Barisal Division','বরিশাল বিভাগ',null,'outlet_grid','local-newspaper','regional',8,false,12,'#1E7BA8',true)
on conflict (slug) do nothing;

-- Outlets (linked to categories by slug)
insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'bdnews24', 'বিডিনিউজ২৪', 'https://bdnews24.com', true, 0, true
from public.categories c where c.slug='online-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Jagonews24', 'জাগোনিউজ২৪', 'https://www.jagonews24.com', true, 1, true
from public.categories c where c.slug='online-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Bangla News 24', 'বাংলানিউজ২৪', 'https://www.banglanews24.com', true, 2, true
from public.categories c where c.slug='online-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Bangla Tribune', 'বাংলা ট্রিবিউন', 'https://www.banglatribune.com', true, 3, true
from public.categories c where c.slug='online-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Risingbd', null, 'https://www.risingbd.com', true, 4, true
from public.categories c where c.slug='online-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'BBC Bangla', 'বিবিসি বাংলা', 'https://www.bbc.com/bengali', true, 5, true
from public.categories c where c.slug='online-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Dhaka Post', 'ঢাকা পোস্ট', 'https://www.dhakapost.com', true, 6, true
from public.categories c where c.slug='online-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Dhaka Times', 'ঢাকা টাইমস', 'https://www.dhakatimes24.com', true, 7, true
from public.categories c where c.slug='online-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Amader Shomoy', 'আমাদের সময়', 'https://www.dainikamadershomoy.com', true, 8, true
from public.categories c where c.slug='online-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'BD Cric Time', null, 'https://bdcrictime.com', true, 9, true
from public.categories c where c.slug='online-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Probashir Diganta', 'প্রবাসীর দিগন্ত', 'https://probashirdiganta.com', false, 10, true
from public.categories c where c.slug='online-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'DW Bangla', null, 'https://www.dw.com/bn', false, 11, true
from public.categories c where c.slug='online-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Dainik Shiksha', 'দৈনিক শিক্ষা', 'https://www.dainikshiksha.com', false, 12, true
from public.categories c where c.slug='online-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Barta24', 'বার্তা২৪', 'https://barta24.com', false, 13, true
from public.categories c where c.slug='online-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'MTnews24', null, 'https://mtnews24.com', false, 14, true
from public.categories c where c.slug='online-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Medi Voice', 'মেডি ভয়েস', 'https://medivoicebd.com', false, 15, true
from public.categories c where c.slug='online-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Our Islam', null, 'https://ourislam24.com', false, 16, true
from public.categories c where c.slug='online-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Sara Bangla', 'সারাবাংলা', 'https://sarabangla.net', false, 17, true
from public.categories c where c.slug='online-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'VOA Bangla', null, 'https://www.voabangla.com', false, 18, true
from public.categories c where c.slug='online-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Somoyer Konthosor', 'সময়ের কণ্ঠস্বর', 'https://www.somoyerkonthosor.com', false, 19, true
from public.categories c where c.slug='online-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Shiksha Barta', 'শিক্ষা বার্তা', 'https://shikshabarta.com', false, 20, true
from public.categories c where c.slug='online-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Sonali News', 'সোনালী নিউজ', 'https://www.sonalinews.com', false, 21, true
from public.categories c where c.slug='online-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'BD24Live', null, 'https://www.bd24live.com', false, 22, true
from public.categories c where c.slug='online-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Barta Bazar', 'বার্তা বাজার', 'https://bartabazar.com', false, 23, true
from public.categories c where c.slug='online-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Dhaka Today', 'ঢাকা টুডে', 'https://www.dhakatoday.com', false, 24, true
from public.categories c where c.slug='online-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Prothom Alo', 'প্রথম আলো', 'https://www.prothomalo.com', true, 0, true
from public.categories c where c.slug='national-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Kaler Kantho', 'কালের কণ্ঠ', 'https://www.kalerkantho.com', true, 1, true
from public.categories c where c.slug='national-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Jugantor', 'যুগান্তর', 'https://www.jugantor.com', true, 2, true
from public.categories c where c.slug='national-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Bangladesh Pratidin', 'বাংলাদেশ প্রতিদিন', 'https://www.bd-pratidin.com', true, 3, true
from public.categories c where c.slug='national-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Samakal', 'সমকাল', 'https://samakal.com', true, 4, true
from public.categories c where c.slug='national-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'The Daily Ittefaq', 'দৈনিক ইত্তেফাক', 'https://www.ittefaq.com.bd', false, 5, true
from public.categories c where c.slug='national-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Daily Janakantha', 'দৈনিক জনকণ্ঠ', 'https://www.dailyjanakantha.com', false, 6, true
from public.categories c where c.slug='national-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Kal Bela', 'কালবেলা', 'https://www.kalbela.com', false, 7, true
from public.categories c where c.slug='national-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Jaijaidin', 'যায়যায়দিন', 'https://www.jaijaidinbd.com', false, 8, true
from public.categories c where c.slug='national-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'The Daily Star Bangla', 'দ্য ডেইলি স্টার বাংলা', 'https://bangla.thedailystar.net', false, 9, true
from public.categories c where c.slug='national-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Desh Rupantor', 'দেশ রূপান্তর', 'https://www.deshrupantor.com', false, 10, true
from public.categories c where c.slug='national-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Ajker Patrika', 'আজকের পত্রিকা', 'https://www.ajkerpatrika.com', false, 11, true
from public.categories c where c.slug='national-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Amar Sangbad', 'আমার সংবাদ', 'https://www.amarsangbad.com', false, 12, true
from public.categories c where c.slug='national-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Dainik Bangla', 'দৈনিক বাংলা', 'https://www.dainikbangla.com.bd', false, 13, true
from public.categories c where c.slug='national-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Protidiner Sangbad', 'প্রতিদিনের সংবাদ', 'https://www.protidinersangbad.com', false, 14, true
from public.categories c where c.slug='national-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Daily Ajker Darpon', 'আজকের দর্পণ', 'https://dainikajkerdarpan.com', false, 15, true
from public.categories c where c.slug='national-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Bangladesh Journal', 'বাংলাদেশ জার্নাল', 'https://www.bd-journal.com', false, 16, true
from public.categories c where c.slug='national-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Alokito Bangladesh', 'আলোকিত বাংলাদেশ', 'https://www.alokitobangladesh.com', false, 17, true
from public.categories c where c.slug='national-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'The Sangbad', 'সংবাদ', 'https://sangbad.net.bd', false, 18, true
from public.categories c where c.slug='national-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Daily Manobkantha', 'মানবকণ্ঠ', 'https://www.manobkantha.com.bd', false, 19, true
from public.categories c where c.slug='national-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Ajkaler Khobor', 'আজকালের খবর', 'https://www.ajkalerkhabor.com', false, 20, true
from public.categories c where c.slug='national-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Daily Sangram', 'সংগ্রাম', 'https://dailysangram.com', false, 21, true
from public.categories c where c.slug='national-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Protidiner Bangladesh', 'প্রতিদিনের বাংলাদেশ', 'https://www.protidinerbangladesh.com', false, 22, true
from public.categories c where c.slug='national-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Sokaler Somoy', 'সকালের সময়', 'https://www.shokalersomoy.com', false, 23, true
from public.categories c where c.slug='national-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Bonik Barta', 'বণিক বার্তা', 'https://bonikbarta.com', false, 24, true
from public.categories c where c.slug='national-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Naya Diganta', 'নয়া দিগন্ত', 'https://www.dailynayadiganta.com', false, 25, true
from public.categories c where c.slug='national-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Manab Zamin', 'মানবজমিন', 'https://mzamin.com', false, 26, true
from public.categories c where c.slug='national-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Daily Inqilab', 'দৈনিক ইনকিলাব', 'https://www.dailyinqilab.com', false, 27, true
from public.categories c where c.slug='national-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Bhorer Kagoj', 'ভোরের কাগজ', 'https://www.bhorerkagoj.com', false, 28, true
from public.categories c where c.slug='national-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Somoy TV', 'সময় টিভি', 'https://www.somoynews.tv', true, 0, true
from public.categories c where c.slug='tv-news'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Jamuna TV', 'যমুনা টিভি', 'https://jamuna.tv', true, 1, true
from public.categories c where c.slug='tv-news'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Channel 24', 'চ্যানেল ২৪', 'https://www.channel24bd.tv', true, 2, true
from public.categories c where c.slug='tv-news'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'DBC News', 'ডিবিসি নিউজ', 'https://www.dbcnews.tv', true, 3, true
from public.categories c where c.slug='tv-news'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Ekattor TV', 'একাত্তর টিভি', 'https://ekattor.tv', true, 4, true
from public.categories c where c.slug='tv-news'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'NTV', 'এনটিভি', 'https://www.ntvbd.com', false, 5, true
from public.categories c where c.slug='tv-news'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Channel i', 'চ্যানেল আই', 'https://www.channelionline.com', false, 6, true
from public.categories c where c.slug='tv-news'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'ATN News', 'এটিএন নিউজ', 'https://www.atnnewstv.com', false, 7, true
from public.categories c where c.slug='tv-news'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'RTV', 'আরটিভি', 'https://www.rtvonline.com', false, 8, true
from public.categories c where c.slug='tv-news'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Independent TV', 'ইন্ডিপেন্ডেন্ট টিভি', 'https://www.itvbd.com', false, 9, true
from public.categories c where c.slug='tv-news'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'News24', 'নিউজ২৪', 'https://www.news24bd.tv', false, 10, true
from public.categories c where c.slug='tv-news'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Bangla Vision', 'বাংলাভিশন', 'https://www.banglavision.tv', false, 11, true
from public.categories c where c.slug='tv-news'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Radio Today 89.6', null, 'https://www.radiotoday.fm', true, 0, true
from public.categories c where c.slug='fm-radio'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Jago FM 94.4', null, 'https://www.jagofm.com', true, 1, true
from public.categories c where c.slug='fm-radio'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Radio Capital 94.8', null, 'https://www.radiocapital.com.bd', true, 2, true
from public.categories c where c.slug='fm-radio'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Radio Shadhin 92.4', null, 'https://www.radioshadhin.com', true, 3, true
from public.categories c where c.slug='fm-radio'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Peoples Radio 91.6', null, 'https://www.peoplesradio.com.bd', true, 4, true
from public.categories c where c.slug='fm-radio'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Radio Dhoni 91.2', null, 'https://www.radiodhoni.com', false, 5, true
from public.categories c where c.slug='fm-radio'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Radio Foorti 88.0', null, 'https://www.radiofoorti.fm', false, 6, true
from public.categories c where c.slug='fm-radio'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'BBC Bangla Radio', 'বিবিসি বাংলা রেডিও', 'https://www.bbc.com/bengali', false, 7, true
from public.categories c where c.slug='fm-radio'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Spice FM 96.4', null, 'https://www.spicefmbd.com', false, 8, true
from public.categories c where c.slug='fm-radio'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Dhaka FM 90.4', null, 'https://www.dhakafm.com.bd', false, 9, true
from public.categories c where c.slug='fm-radio'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Bangladesh National Portal', 'বাংলাদেশ জাতীয় তথ্য বাতায়ন', 'https://bangladesh.gov.bd', true, 0, true
from public.categories c where c.slug='government-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Ministry of Finance', 'অর্থ মন্ত্রণালয়', 'https://mof.gov.bd', true, 1, true
from public.categories c where c.slug='government-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Ministry of Science & Technology', 'বিজ্ঞান ও প্রযুক্তি মন্ত্রণালয়', 'https://most.gov.bd', false, 2, true
from public.categories c where c.slug='government-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Ministry of Food', 'খাদ্য মন্ত্রণালয়', 'https://mofood.gov.bd', false, 3, true
from public.categories c where c.slug='government-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Ministry of Industries', 'শিল্প মন্ত্রণালয়', 'https://moind.gov.bd', false, 4, true
from public.categories c where c.slug='government-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Ministry of Education', 'শিক্ষা মন্ত্রণালয়', 'https://moedu.gov.bd', false, 5, true
from public.categories c where c.slug='government-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Ministry of Health & Family Welfare', 'স্বাস্থ্য মন্ত্রণালয়', 'https://mohfw.gov.bd', false, 6, true
from public.categories c where c.slug='government-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Ministry of Home Affairs', 'স্বরাষ্ট্র মন্ত্রণালয়', 'https://mha.gov.bd', false, 7, true
from public.categories c where c.slug='government-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Ministry of Foreign Affairs', 'পররাষ্ট্র মন্ত্রণালয়', 'https://mofa.gov.bd', false, 8, true
from public.categories c where c.slug='government-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Ministry of Agriculture', 'কৃষি মন্ত্রণালয়', 'https://moa.gov.bd', false, 9, true
from public.categories c where c.slug='government-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'BD Jobs', null, 'https://www.bdjobs.com', true, 0, true
from public.categories c where c.slug='job-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Bikroy Jobs', null, 'https://bikroy.com/en/jobs', true, 1, true
from public.categories c where c.slug='job-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'BDJobs.com.bd', null, 'https://bdjobs.com.bd', true, 2, true
from public.categories c where c.slug='job-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'BD Jobs Today', null, 'https://www.bdjobstoday.com', false, 3, true
from public.categories c where c.slug='job-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Chakri Khobor', 'চাকরির খবর', 'https://chakrirkhobor.net', false, 4, true
from public.categories c where c.slug='job-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Skill Jobs', null, 'https://skill.jobs', false, 5, true
from public.categories c where c.slug='job-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'NRB Jobs', null, 'https://www.nrbjobs.com', false, 6, true
from public.categories c where c.slug='job-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Job.com.bd', null, 'https://job.com.bd', false, 7, true
from public.categories c where c.slug='job-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Careerjet', null, 'https://www.careerjet.com.bd', false, 8, true
from public.categories c where c.slug='job-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Shomvob', null, 'https://shomvob.co', false, 9, true
from public.categories c where c.slug='job-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'My Jobs', null, 'https://myjobs.com.bd', false, 10, true
from public.categories c where c.slug='job-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'eJobs', null, 'https://ejobsbd.com', false, 11, true
from public.categories c where c.slug='job-portals'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'The Daily Star', null, 'https://www.thedailystar.net', true, 0, true
from public.categories c where c.slug='english-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'The Business Standard', null, 'https://www.tbsnews.net', true, 1, true
from public.categories c where c.slug='english-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Dhaka Tribune', null, 'https://www.dhakatribune.com', true, 2, true
from public.categories c where c.slug='english-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'New Age', null, 'https://www.newagebd.net', false, 3, true
from public.categories c where c.slug='english-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'The Financial Express', null, 'https://thefinancialexpress.com.bd', false, 4, true
from public.categories c where c.slug='english-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'The Independent', null, 'https://www.theindependentbd.com', false, 5, true
from public.categories c where c.slug='english-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Daily Sun', null, 'https://www.daily-sun.com', false, 6, true
from public.categories c where c.slug='english-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'The Daily Observer', null, 'https://www.observerbd.com', false, 7, true
from public.categories c where c.slug='english-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Bangladesh Post', null, 'https://bangladeshpost.net', false, 8, true
from public.categories c where c.slug='english-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'The Daily Messenger', null, 'https://www.dailymessenger.net', false, 9, true
from public.categories c where c.slug='english-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Dhaka Stock Exchange', null, 'https://dsebd.org', true, 0, true
from public.categories c where c.slug='stock-market'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Chittagong Stock Exchange', null, 'https://www.cse.com.bd', true, 1, true
from public.categories c where c.slug='stock-market'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Bonik Barta', 'বণিক বার্তা', 'https://bonikbarta.com', false, 2, true
from public.categories c where c.slug='stock-market'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Share Biz', 'শেয়ার বিজ', 'https://sharebiz.net', false, 3, true
from public.categories c where c.slug='stock-market'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Arthosuchak', 'অর্থসূচক', 'https://arthosuchak.com', false, 4, true
from public.categories c where c.slug='stock-market'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'The Business Standard', null, 'https://www.tbsnews.net', false, 5, true
from public.categories c where c.slug='stock-market'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Business Insider Bangladesh', null, 'https://www.businessinsiderbd.com', false, 6, true
from public.categories c where c.slug='stock-market'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Asomiya Pratidin', 'অসমীয়া প্রতিদিন', 'https://www.asomiyapratidin.in', true, 0, true
from public.categories c where c.slug='assam-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Niyomiya Barta', 'নিয়মিয়া বার্তা', 'https://niyomiyabarta.org', true, 1, true
from public.categories c where c.slug='assam-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Assam Tribune', null, 'https://assamtribune.com', false, 2, true
from public.categories c where c.slug='assam-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Ganaadhikar', 'গণ অধিকার', 'https://www.ganadhikar.in', false, 3, true
from public.categories c where c.slug='assam-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Nenow', null, 'https://nenow.in', false, 4, true
from public.categories c where c.slug='assam-newspapers'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Prothom Alo ePaper', 'প্রথম আলো ই-পেপার', 'https://epaper.prothomalo.com', true, 0, true
from public.categories c where c.slug='epaper'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Kaler Kantho ePaper', 'কালের কণ্ঠ ই-পেপার', 'https://epaper.kalerkantho.com', true, 1, true
from public.categories c where c.slug='epaper'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Jugantor ePaper', 'যুগান্তর ই-পেপার', 'https://epaper.jugantor.com', true, 2, true
from public.categories c where c.slug='epaper'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Ittefaq ePaper', 'ইত্তেফাক ই-পেপার', 'https://epaper.ittefaq.com.bd', false, 3, true
from public.categories c where c.slug='epaper'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Samakal ePaper', 'সমকাল ই-পেপার', 'https://epaper.samakal.com', false, 4, true
from public.categories c where c.slug='epaper'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Bangladesh Pratidin ePaper', 'বাংলাদেশ প্রতিদিন ই-পেপার', 'https://epaper.bd-pratidin.com', false, 5, true
from public.categories c where c.slug='epaper'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Daily Star ePaper', null, 'https://epaper.thedailystar.net', false, 6, true
from public.categories c where c.slug='epaper'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Manab Zamin ePaper', 'মানবজমিন ই-পেপার', 'https://mzamin.com/epaper', false, 7, true
from public.categories c where c.slug='epaper'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Naya Diganta ePaper', 'নয়া দিগন্ত ই-পেপার', 'https://epaper.dailynayadiganta.com', false, 8, true
from public.categories c where c.slug='epaper'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Janakantha ePaper', 'জনকণ্ঠ ই-পেপার', 'https://epaper.dailyjanakantha.com', false, 9, true
from public.categories c where c.slug='epaper'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Dainik Dhakar Barta', null, 'https://www.dhakarbarta.com', false, 0, true
from public.categories c where c.slug='dhaka-division'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Gazipur Barta', null, 'https://gazipurbarta.com', false, 1, true
from public.categories c where c.slug='dhaka-division'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Narayanganj Times', null, 'https://narayanganjtimes.com', false, 2, true
from public.categories c where c.slug='dhaka-division'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Tangail Somachar', null, 'https://tangailsomachar.com', false, 3, true
from public.categories c where c.slug='dhaka-division'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Mymensingh Pratidin', null, 'https://mymensinghpratidin.com', false, 0, true
from public.categories c where c.slug='mymensingh-division'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Dainik Jahan', null, 'https://dainikjahan.com', false, 1, true
from public.categories c where c.slug='mymensingh-division'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Netrokona Barta', null, 'https://netrokonabarta.com', false, 2, true
from public.categories c where c.slug='mymensingh-division'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Sylhet Today 24', null, 'https://www.sylhettoday24.news', false, 0, true
from public.categories c where c.slug='sylhet-division'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Daily Sylhet', null, 'https://dailysylhet.com', false, 1, true
from public.categories c where c.slug='sylhet-division'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Sylhet Mirror', null, 'https://sylhetmirror.com', false, 2, true
from public.categories c where c.slug='sylhet-division'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Habiganj Barta', null, 'https://habiganjbarta.com', false, 3, true
from public.categories c where c.slug='sylhet-division'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Dainik Azadi', null, 'https://dainikazadi.net', false, 0, true
from public.categories c where c.slug='chattogram-division'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Dainik Purbokone', null, 'https://dainikpurbokone.net', false, 1, true
from public.categories c where c.slug='chattogram-division'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'CTG News', null, 'https://ctgnews.com', false, 2, true
from public.categories c where c.slug='chattogram-division'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Coxsbazar News', null, 'https://coxsbazarnews.com', false, 3, true
from public.categories c where c.slug='chattogram-division'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Dainik Dabanol', null, 'https://dainikdabanol.com', false, 0, true
from public.categories c where c.slug='rangpur-division'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Rangpur Barta', null, 'https://rangpurbarta.com', false, 1, true
from public.categories c where c.slug='rangpur-division'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Dinajpur Sangbad', null, 'https://dinajpurnews.com', false, 2, true
from public.categories c where c.slug='rangpur-division'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Dainik Purbanchal', null, 'https://dainikpurbanchal.com', false, 0, true
from public.categories c where c.slug='khulna-division'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Khulna News', null, 'https://khulnanews.com', false, 1, true
from public.categories c where c.slug='khulna-division'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Jashore Barta', null, 'https://jashorbarta.com', false, 2, true
from public.categories c where c.slug='khulna-division'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Sonar Desh', null, 'https://www.sonardesh.com', false, 0, true
from public.categories c where c.slug='rajshahi-division'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Dainik Barta', null, 'https://dainikbarta.net', false, 1, true
from public.categories c where c.slug='rajshahi-division'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Rajshahi News', null, 'https://rajshahinews24.com', false, 2, true
from public.categories c where c.slug='rajshahi-division'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Natore Barta', null, 'https://natorebarta.com', false, 3, true
from public.categories c where c.slug='rajshahi-division'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Dainik Barishal Barta', null, 'https://barishalbarta.com', false, 0, true
from public.categories c where c.slug='barisal-division'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Barisal Khabor', null, 'https://barisalkhabar.com', false, 1, true
from public.categories c where c.slug='barisal-division'
on conflict (category_id,name) do nothing;

insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)
select c.id, 'Bhola News', null, 'https://bholanews.com', false, 2, true
from public.categories c where c.slug='barisal-division'
on conflict (category_id,name) do nothing;

-- Pretty /read/[slug] handles (unique)
update public.outlets set slug = regexp_replace(lower(regexp_replace(trim(name), '[^a-zA-Z0-9]+', '-', 'g')), '^-+|-+$', '', 'g') where slug is null or slug = '';
with ranked as (select id, slug, row_number() over (partition by slug order by created_at, id) as rn from public.outlets)
update public.outlets o set slug = o.slug || '-' || r.rn from ranked r where o.id = r.id and r.rn > 1;
create unique index if not exists outlets_slug_idx on public.outlets(slug);
