/**
 * Generates supabase/seed.sql from lib/seed-data.ts (single source of truth).
 * Run:  npx tsx scripts/gen-seed.ts
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { CATEGORIES, OUTLETS } from "../lib/seed-data";
import { DEFAULT_HOME_LIMIT } from "../lib/site-config";

const esc = (v: string | null | undefined): string =>
  v === null || v === undefined || v === ""
    ? "null"
    : `'${v.replace(/'/g, "''")}'`;
const bool = (v: boolean | undefined) => (v ? "true" : "false");
const int = (v: number | undefined) => String(v ?? 0);

const lines: string[] = [
  "-- AUTO-GENERATED by scripts/gen-seed.ts — do not edit by hand.",
  "-- Run after schema.sql. Safe to re-run (on conflict do nothing).",
  "",
  "insert into public.categories",
  "  (slug,title,title_bn,description,section_type,parent_slug,group_key,sort_order,show_on_home,home_limit,accent,is_active)",
  "values",
];

lines.push(
  CATEGORIES.map(
    (c) =>
      `  (${esc(c.slug)},${esc(c.title)},${esc(c.title_bn)},${esc(c.description)},` +
      `${esc(c.section_type)},${esc(c.parent_slug ?? null)},${esc(c.group)},` +
      `${int(c.sort_order)},${bool(c.home)},${int(c.home_limit ?? DEFAULT_HOME_LIMIT)},` +
      `${esc(c.accent ?? null)},true)`,
  ).join(",\n") + "\non conflict (slug) do nothing;",
);

lines.push("", "-- Outlets (linked to categories by slug)");
for (const o of OUTLETS) {
  lines.push(
    `insert into public.outlets (category_id,name,name_bn,url,is_featured,sort_order,is_active)`,
    `select c.id, ${esc(o.name)}, ${esc(o.name_bn ?? null)}, ${esc(o.url)}, ${bool(
      o.is_featured,
    )}, ${int(o.sort_order)}, true`,
    `from public.categories c where c.slug=${esc(o.category_slug)}`,
    `on conflict (category_id,name) do nothing;`,
    "",
  );
}

lines.push(
  "-- Pretty /read/[slug] handles (unique)",
  "update public.outlets set slug = regexp_replace(lower(regexp_replace(trim(name), '[^a-zA-Z0-9]+', '-', 'g')), '^-+|-+$', '', 'g') where slug is null or slug = '';",
  "with ranked as (select id, slug, row_number() over (partition by slug order by created_at, id) as rn from public.outlets)",
  "update public.outlets o set slug = o.slug || '-' || r.rn from ranked r where o.id = r.id and r.rn > 1;",
  "create unique index if not exists outlets_slug_idx on public.outlets(slug);",
  "",
);

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "supabase", "seed.sql");
writeFileSync(out, lines.join("\n"), "utf8");
console.log(
  `Wrote ${out} — ${CATEGORIES.length} categories, ${OUTLETS.length} outlets.`,
);
