-- Migration 0017 - de-duplicate this site's copy from allbanglapaper.com.
--
-- Both directories list the same 488 outlets. Until now they also shared
-- every category title, every category description and every blog title
-- word for word, which is the signal Google uses to decide that one of two
-- near-identical sites is a copy of the other and filter it out.
--
-- Category titles here move to 'List' phrasing, which is on-brand for this
-- site and cost nothing to change because it holds no rankings yet; the
-- older site keeps the terms it already ranks for. Division titles are left
-- alone - 'Dhaka Division' is simply the name of the place, and both sites
-- are entitled to it. Duplicate prose is the problem, not shared nouns.
--
-- Idempotent: re-running rewrites the same values.

update public.categories set title = 'Bangla Newspaper List', description = 'Every national Bangla daily in Bangladesh, gathered as one list. These are the mass-circulation papers printed in Dhaka and distributed nationwide, each running its own newsroom across politics, parliament, the economy, crime, courts, education, sport and district reporting. Most publish continuously online through the day and post a separate ePaper of the printed edition each morning. Which one you read matters: Bangladeshi dailies differ sharply in editorial line, in how much space they give opposition politics or business coverage, and in whether their strength is breaking news or long-form reporting. Reading two or three side by side gives a fuller picture than any single title. Every name below opens that newspaper''s own official website. Nothing is reproduced here and no registration is required to follow any of them.' where slug = 'national-newspapers';
update public.categories set title = 'Online News Portal List', description = 'Bangladesh''s digital-only news publishers, listed together. Unlike the print dailies these outlets have no paper edition at all. They were built for the web, publish as stories break rather than to a nightly deadline, and often carry a district story hours before the national papers reach it. Coverage runs across national politics, business, technology, entertainment, sport and live event reporting. Because there is no print run to fund, most rely entirely on advertising and stay free to read. The trade-off is variable editorial standards, so it is worth knowing which portals maintain proper newsrooms and which mainly aggregate. This list gives you the addresses in one place, and each link goes to the publisher''s own site so you can judge the reporting for yourself.' where slug = 'online-portals';
update public.categories set title = 'Bangla ePaper List', description = 'Digital editions of Bangladesh''s printed newspapers, collected in one list. An ePaper is not a news website. It is a page-for-page facsimile of the paper sold at the stall that morning, with the same layout, the same column placement, the same photographs and the same advertisements. That fixed form is why people use them: you can see what a paper led with on a given day, read the editorial exactly where it was printed, and archive a page. They are particularly useful for researchers tracking how a story was covered, for readers abroad who cannot buy a physical copy, and for anyone who simply prefers reading a newspaper rather than a feed. Most Bangladeshi publishers post the day''s edition free by early morning.' where slug = 'epaper';
update public.categories set title = 'English Newspaper List', description = 'Bangladeshi newspapers published in English, listed together. These are not translations of the Bangla dailies. They are separately edited papers with their own newsrooms, and they often cover a story differently, with more weight on diplomacy, trade, garments, foreign investment and regional affairs. Their readership explains the emphasis: diplomats, business people, development staff, researchers, students preparing for English-medium exams, and Bangladeshis living abroad. For anyone studying the country from outside, these are usually the most accessible primary sources available. Several also publish an ePaper edition alongside the website. Every link here opens the newspaper''s own official site, free to read, with no subscription required for the great majority of their coverage.' where slug = 'english-newspapers';
update public.categories set title = 'Indian Newspaper List', description = 'Major Indian newspapers, listed for readers following news across the border. India''s press is enormous and multilingual, with English titles circulating nationally and language papers dominating individual states. Collected here are the widely read national and regional titles most useful to a Bangladeshi reader: coverage of Indian politics and the economy, of West Bengal in particular, and of the bilateral questions that affect both countries such as river water sharing, border management, trade and transit. Reading Indian reporting alongside Bangladeshi reporting on the same event is often the fastest way to see where the two national narratives diverge. All titles link to their own official websites and the large majority publish free online editions.' where slug = 'india-newspapers';
update public.categories set title = 'Share Bazar Newspaper List', description = 'Financial and share-market publications, listed for investors following DSE and CSE. These outlets cover what the general dailies treat only in passing: daily index movement, turnover, block trades, circuit breakers, IPO subscriptions and lotteries, rights issues, dividend declarations, quarterly results, board meeting notices and Bangladesh Bank policy decisions. For anyone holding a BO account, these are the papers carrying announcements before they filter into general news. Several also publish sector analysis on banking, textiles, pharmaceuticals and cement. One caution worth stating plainly: market commentary is not investment advice, and nothing in these publications or in this list should be treated as a recommendation to buy or sell. Every link opens the publisher''s own official site.' where slug = 'stock-market';
update public.categories set title = 'Regional Newspaper List by Division', description = 'Newspapers published outside Dhaka, organised by Bangladesh''s eight administrative divisions. Regional papers cover what the national dailies rarely have space for: upazila council decisions, local land disputes, river erosion, school and college affairs, district hospital conditions, crop prices at the local haat, and the municipal politics that shape daily life in a place. For anyone with roots in a particular district, this is often the only place that news appears in print at all. It is also the layer researchers and journalists reach for when a national story turns out to have started locally. Choose your division below, whether Dhaka, Chattogram, Rajshahi, Khulna, Barishal, Sylhet, Rangpur or Mymensingh, to see the titles published in that region.' where slug = 'local-newspaper';
update public.categories set title = 'Bangla Magazine List', description = 'Bangla-language magazines and periodicals, listed together. Magazines work on a different rhythm from newspapers. Published weekly, fortnightly or monthly, they trade immediacy for depth, running long-form reporting, literary writing, criticism, interviews and photo essays that a daily has no room for. The range here covers literature and little magazines, women''s and family titles, science and technology, health, film and culture, and youth and campus publications. Bangla periodical writing has a long history, and much of the country''s essay and short-story tradition still appears first in these pages. Several titles now publish full editions online alongside print. Each entry links to the magazine''s own official website or its digital edition, free to read where the publisher offers it.' where slug = 'bangla-magazine';
update public.categories set title = 'TV News Channel List', description = 'Bangladeshi television news channels and their online platforms, listed together. Television remains the most-watched news source in Bangladesh, and nearly every channel now streams live online and posts bulletins, talk shows and investigative segments to its website and video platforms, which means you can follow them from a phone anywhere in the world rather than only from a set at home. Coverage spans rolling national news, parliamentary sessions, election reporting, current-affairs debate programmes and district correspondents'' packages. Talk shows in particular carry political argument that print often reports only after the fact. Each entry links to the channel''s own official site or streaming page, where live output and archived bulletins are generally free to watch.' where slug = 'tv-news';
update public.categories set title = 'FM Radio Station List', description = 'FM radio stations broadcasting in Bangladesh, with their online streams. Radio held on where other old media faded, largely because of traffic: for anyone stuck on a Dhaka road, an FM station is the one medium that works hands-free. Programming mixes Bangla and English music, live phone-ins, drive-time shows, hourly news, weather, traffic bulletins and late-night request programmes, and the stations have become a significant platform for new Bangladeshi musicians. Community stations also carry public-health and agricultural information into areas where they matter most. Most broadcasters now stream live through their own websites and apps, so a station is reachable well outside its transmitter range. Each entry links to the station''s own official site or stream.' where slug = 'fm-radio';
update public.categories set title = 'Job Site List', description = 'Employment websites and recruitment portals used in Bangladesh, listed together. These are where most formal vacancies are actually posted: government and semi-government circulars, bank recruitment, NGO and development positions, private-sector openings, teaching posts, garments and manufacturing roles, and IT and freelance work. Several also host the CV databases that recruiters search directly, so registering can matter as much as applying. Government job circulars in particular follow their own publication cycle and deadlines, and missing the window usually means waiting for the next one. Alongside listings, many of these sites publish exam notices, admit-card releases and result announcements. Each entry links to the portal''s own official website. Applications are always made on the portal''s own site, never through this list.' where slug = 'job-portals';
update public.categories set title = 'World Newspaper List', description = 'Internationally significant newspapers, listed for readers following global affairs. These are the titles whose reporting sets the agenda well beyond their own countries, papers of record whose investigations are picked up worldwide and whose foreign desks still maintain correspondents in places most outlets have long since left. For a Bangladeshi reader they serve two purposes: following world events directly rather than through wire summaries, and seeing how international coverage frames South Asia, climate and migration stories that affect the country. They are also widely used by students working on English reading and by anyone studying how serious journalism is structured. Some operate paywalls, though most allow a number of free articles. Every entry links to the publisher''s own official website.' where slug = 'top-newspaper-in-the-world';
update public.categories set title = 'International Newspaper List', description = 'Newspapers published outside Bangladesh and India, listed by region. Bangladeshi readers follow the foreign press for specific reasons. Several million Bangladeshis work in the Gulf, Malaysia and Singapore and rely on local reporting there for labour rules and visa changes. Diaspora communities in the UK, US, Canada, Italy and Australia follow the countries they live in. Students preparing to study abroad read the national press of where they are heading. This section collects those titles in one place rather than leaving you to search country by country. Coverage naturally reflects each country''s own priorities, which is much of the value, because it shows how an event looks from somewhere else. Each entry links to the publisher''s own official website.' where slug = 'international-newspapers';
update public.categories set title = 'International Newspaper List', description = 'Newspapers from around the world, grouped for readers following news beyond Bangladesh and India. The section is built around how Bangladeshi readers actually use the foreign press: Gulf and Southeast Asian titles for the millions working abroad and the labour, wage and visa reporting that affects them directly; British, American, Canadian and Australian papers for diaspora communities and for students heading to those countries; and regional titles for anyone tracking a specific part of the world. Reading a country''s own press rather than wire copy about it is usually the difference between knowing what happened and understanding why it mattered there. Every entry links to the publisher''s own official website, and most operate free online editions.' where slug = 'international-newspaper';
update public.categories set title = 'Dhaka Division', description = 'Newspapers published across Dhaka division, listed by their home district. Beyond the national dailies printed in the capital, this division supports a dense layer of district and upazila papers covering Gazipur, Narayanganj, Tangail, Kishoreganj, Manikganj, Munshiganj, Narsingdi, Faridpur, Gopalganj, Madaripur, Rajbari and Shariatpur. Their reporting is close to the ground: municipal budgets and tenders, land and river-sand disputes, industrial and garment-belt labour issues, school results, road and bridge works, and the union and upazila politics that national coverage reaches only when something goes badly wrong. For readers with family or property in these districts, and for journalists tracing where a national story began, they are frequently the only published record. Each title links to its own official website.' where slug = 'dhaka-division';
update public.categories set title = 'Chattogram Division', description = 'Newspapers published across Chattogram division, listed by district. The division carries a distinct news agenda shaped by the port, the shipbreaking yards, the export processing zones and the hill districts. Local papers here cover port and customs operations, shipping and freight, tea and rubber estates, fisheries, and the particular political and land questions of Rangamati, Khagrachhari and Bandarban, alongside Cox''s Bazar reporting on tourism, fishing and the refugee settlements. Cyclone and landslide coverage is another local specialism, reported with a detail and urgency the national press rarely matches. For anyone following the division''s economy or its regional politics, these titles carry material that never reaches Dhaka print. Each links to its own official website.' where slug = 'chattogram-division';
update public.categories set title = 'Rajshahi Division', description = 'Newspapers published across Rajshahi division, listed by district. This is Bangladesh''s agricultural heartland, and the local press reflects it: paddy and mango harvests, silk production, groundwater and irrigation, Barind tract drought, fertiliser supply and procurement prices appear here as front-page news rather than as farming briefs. Papers across Rajshahi, Bogura, Pabna, Sirajganj, Natore, Naogaon, Chapainawabganj and Joypurhat also cover university affairs, border and enclave questions, and municipal politics in detail. Because agricultural distress usually shows up in district reporting long before it reaches national coverage, these titles are a useful early indicator for anyone tracking rural conditions. Each entry links to the newspaper''s own official website.' where slug = 'rajshahi-division';
update public.categories set title = 'Khulna Division', description = 'Newspapers published across Khulna division, listed by district. The division''s reporting is dominated by water and what it does: shrimp and prawn farming, salinity intrusion, embankment failures, Sundarbans conservation and the recurring cyclones that make landfall along this coast. Papers in Khulna, Jessore, Satkhira, Bagerhat, Kushtia, Jhenaidah, Magura, Meherpur, Narail and Chuadanga also cover the Benapole land port and cross-border trade, jute mills and their labour disputes, and district-level administration. Coastal reporting from here is often the first account of an approaching storm or a broken embankment, published while national outlets are still confirming. Each title links to its own official website.' where slug = 'khulna-division';
update public.categories set title = 'Barisal Division', description = 'Newspapers published across Barisal division, listed by district. A largely riverine division, and the local press covers what that means in practice: launch and ferry services, river erosion swallowing homesteads, char land disputes, hilsa fishing seasons and bans, and the storm warnings that matter more here than almost anywhere else in the country. Titles across Barisal, Patuakhali, Bhola, Pirojpur, Barguna and Jhalokati also report municipal politics, embankment and cyclone-shelter works, and agricultural conditions on the chars. For families spread between Dhaka and these districts, and for anyone tracking climate displacement, this reporting is the closest available record. Each entry links to the newspaper''s own official website.' where slug = 'barisal-division';
update public.categories set title = 'Sylhet Division', description = 'Newspapers published across Sylhet division, listed by district. The division has a news agenda of its own, shaped by tea, stone quarrying, gas fields, haor wetlands and one of the largest expatriate populations in the country. Papers in Sylhet, Moulvibazar, Habiganj and Sunamganj cover tea garden labour and wages, flash flooding across the haors, quarry safety, shrine and cultural affairs, and the remittance economy that connects the region to Britain in particular. That diaspora link means these titles are read as much abroad as at home. Flood reporting here is often the earliest published warning for downstream districts. Each entry links to the newspaper''s own official website.' where slug = 'sylhet-division';
update public.categories set title = 'Rangpur Division', description = 'Newspapers published across Rangpur division, listed by district. Reporting from this division tracks conditions the rest of the country hears about late: monga and seasonal food insecurity, Teesta river flows and the water-sharing question, char settlements, tobacco and maize cultivation, and the former enclaves whose administrative absorption is still working through. Papers in Rangpur, Dinajpur, Kurigram, Gaibandha, Nilphamari, Lalmonirhat, Thakurgaon and Panchagarh also cover border incidents, cold-wave deaths in winter, and district administration. Because northern hardship reliably reaches Dhaka print weeks after it begins, these are the titles worth following directly. Each links to its own official website.' where slug = 'rangpur-division';
update public.categories set title = 'Mymensingh Division', description = 'Newspapers published across Mymensingh division, listed by district. Bangladesh''s newest division, and its press covers a mix of agricultural, educational and indigenous affairs: fisheries and hatcheries, the agricultural university and its research, Brahmaputra flooding and erosion, and the Garo and other indigenous communities of the Madhupur and border areas whose land questions receive little national attention. Papers in Mymensingh, Jamalpur, Netrokona and Sherpur also report municipal politics, haor conditions in the north, and flash floods coming down from the hills. For readers following either the region''s agriculture or its indigenous land disputes, these titles carry the detailed record. Each entry links to its own official website.' where slug = 'mymensingh-division';

-- Blog: four posts whose bodies already differed just needed new titles.
update public.posts set title = 'International Newspaper List 2026: 20 Papers Worth Following' where slug like 'top-20-international-newspapers-in-2026%';
update public.posts set title = 'Bangla Newspaper List: How to Find Any Bangladeshi Daily' where slug like 'all-bangla-newspapers-your-complete-directory-%';
update public.posts set title = 'বাংলাদেশের গণমাধ্যম: কেন একাধিক পত্রিকা পড়া জরুরি' where slug like 'why-the-bangladeshi-media-is-important%';
update public.posts set title = 'English Newspaper List 2026: Bangladesh''s English-Language Dailies' where slug like 'all-english-newspaper-2026%';

-- Five posts were identical to the old site body and all. A retitle would
-- not help - duplicate bodies across two domains is the strongest copy
-- signal there is, and the older site holds the search impressions on them.
-- Set back to draft rather than deleted, so the client can rewrite and
-- republish them from Admin -> Posts whenever they want.
update public.posts set published = false where slug = 'all-bangla-newspaper-resource-2026';
update public.posts set published = false where slug = 'all-bangla-newspaper-list-bangla-newspaper-directory';
update public.posts set published = false where slug = 'news-site-earning';
update public.posts set published = false where slug = 'top-30-newspapers-in-the-world-2026';
update public.posts set published = false where slug = 'the-future-of-newspapers-in-bangladesh-today';
